services:

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: spored,nakup,auth
    volumes:
      - ./create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/docker-postgresql-multiple-databases.sh
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - cinecore-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 10s
      retries: 5

  spored:
    image: ghcr.io/prpo-skupina-02/spored:main
    restart: always
    ports:
      - "8080:8080"
    networks:
      - cinecore-net
    depends_on:
      db:
        condition: service_healthy
    environment:
      - LOG_LEVEL=INFO
      - TZ=
      - POSTGRES_IP=db
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE_NAME=spored
      - POSTGRES_TEST_DATABASE_NAME=spored_test
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthcheck"]
      interval: 3s
      timeout: 10s
      retries: 5

  auth:
    image: ghcr.io/prpo-skupina-02/auth:main
    restart: always
    ports:
      - "8082:8080"
    networks:
      - cinecore-net
    depends_on:
      db:
        condition: service_healthy
    environment:
      - LOG_LEVEL=INFO
      - TZ=
      - POSTGRES_IP=db
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE_NAME=auth
      - POSTGRES_TEST_DATABASE_NAME=auth_test
      - JWT_SECRET=production-secret-change-this-in-real-deployment
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthcheck"]
      interval: 3s
      timeout: 10s
      retries: 5

  nakup:
    image: ghcr.io/prpo-skupina-02/nakup:main
    restart: always
    ports:
      - "8081:8080"
    networks:
      - cinecore-net
    depends_on:
      db:
        condition: service_healthy
    environment:
      - LOG_LEVEL=DEBUG
      - TZ=
      - POSTGRES_IP=db
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE_NAME=nakup
      - POSTGRES_TEST_DATABASE_NAME=nakup_test
      - SPORED_HOST=spored:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthcheck"]
      interval: 3s
      timeout: 10s
      retries: 5

  obvestila:
    image: ghcr.io/prpo-skupina-02/obvestila:main
    restart: always
    ports:
      - "8083:8080"
    networks:
      - cinecore-net
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - LOG_LEVEL=INFO
      - TZ=
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_FROM_EMAIL=${RESEND_FROM_EMAIL:-noreply@cinecore.com}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthcheck"]
      interval: 3s
      timeout: 10s
      retries: 5

  reklame:
    image: ghcr.io/prpo-skupina-02/reklame:main
    ports:
      - "8084:8080"
    restart: always
    environment:
      - LOG_LEVEL=DEBUG
      - TZ=
      - SPORED_HOST=spored:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthcheck"]
      interval: 3s
      timeout: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
    networks:
      - cinecore-net
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5

networks:
  cinecore-net:
    name: cinecore-net
    driver: bridge

volumes:
  pgdata:
  rabbitmq-data: