---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: cinecore
type: Opaque
data:
  # CHANGEME
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: cinecore
type: Opaque
data:
  # CHANGEME
  username: Z3Vlc3Q=
  password: Z3Vlc3Q=
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: cinecore
type: Opaque
data:
  # CHANGEME
  JWT_SECRET: cHJvZHVjdGlvbi1zZWNyZXQtY2hhbmdlLXRoaXM=
---
apiVersion: v1
kind: Secret
metadata:
  name: obvestila-secrets
  namespace: cinecore
type: Opaque
data:
  # CHANGEME
  RESEND_API_KEY: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: predlogi-secrets
  namespace: cinecore
type: Opaque
data:
  # CHANGEME
  OPENROUTER_API_KEY: ""
